; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:ESP8266D1Mini]
;platform = espressif8266
;board = esp12e
;framework = arduino
;lib_deps = adafruit/Adafruit MQTT Library@^2.4.3
;monitor_speed = 115200

;uplaod_port = COM5

;debug_tool = esp-prog
;debug_init_break = tbreak setup

[env:esp]
uplaod_port = COM5
platform = espressif32
framework = arduino
lib_deps = adafruit/Adafruit MQTT Library@^2.4.3
board = esp-wrover-kit
monitor_speed = 115200
build_flags =
	; https://docs.espressif.com/projects/esp-idf/en/latest/get-started/get-started-wrover-kit.html#rgb-led
	-D LED_BUILTIN=2


debug_tool = esp-prog
debug_init_break = tbreak setup